### ISSUE TITLE
0.6 release was unsuccessful

### ISSUE THREAD

**Issue by scottyhq** [conda-forge/stac-geoparquet-feedstock#8]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Looks like merging this didn't build correctly https://github.com/conda-forge/stac-geoparquet-feedstock/pull/7, so the latest version is still 0.4.1 on conda-forge. cc @TomAugspurger 

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by TomAugspurger** [comment]
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1035522&view=results finished successfully, and creating a new environment finds 0.6:

```
  stac-geoparquet    conda-forge/noarch::stac-geoparquet-0.6.0-pyhd8ed1ab_0
```
